#include "fs/operations.h"
#include <assert.h>
#include <string.h>

#define GRN "\x1B[32m"
#define RESET "\x1B[0m"

int main() {
    char *str = "BBAAASKJGJHAAASVVZJHVDJSHVZJHBDSJHKAVGKJHSDBGJKIVDLBGSILBDVKIJUSBDJHKVJHDSJHSJHVJSVADJHSJHVHIDSVAJHSAJHKDDASHIVDJUHDSAVJHJDSJVCDSVCVSGJCVDGJAVCGJHAVCGJKDVASUHJCVHUIKJDVUHCVJGHADSVCHGDVGCVCJGDVDJVDVDVDCAVVCJKGAAAAASKJGJHASVJHVZJHVDJSHVJHBDSJHKVGKJHSDBGJKIVDLBGSILBDVKIJUSBDJHKVJHDSJHSJHVJSVADJHSJHVHIDSVAJHSAJHKDDASHIVDJUHDSAVJHJDSJVCDSVCVSGJCVDGJAVCGJHAVCGJKDVASUHJCVHUIKJDVUHCVJGHADSVCHGDVGCVCJGDVDJVDVDVDCAVVCJKGAAAAASKJGJHASVJHVZJHVDJSHVJHBDSJHKVGKJHSDBGJKIVDLBGSILBDVKIJUSBDJHKVJHDSJHSJHVJSVADJHSJHVHIDSVAJHSAJHKDDASHIVDJUHDSAVJHJDSJVCDSVCVSGJCVDGJAVCGJHAVCGJKDVASUHJCVHUIKJDVUHCVJGHADSVCHGDVGCVCJGDVDJVDVDVDCAVVCJKGAAAAASKJGJHASVJHVZJHVDJSHVJHBDSJHKVGKJHSDBGJKIVDLBGSILBDVKIJUSBDJHKVJHDSJHSJHVJSVADJHSJHVHIDSVAJHSAJHKDDASHIVDJUHDSAVJHJDSJVCDSVCVSGJCVDGJAVCGJHAVCGJKDVASUHJCVHUIKJDVUHCVJGHADSVCHGDVGCVCJGDVDJVDVDVDCAVVCJKGAAAAASKJGJHASVJHVZJHVDJSHVJHBDSJHKVGKJHSDBGJKIVDLBGSILBDVKIJUSBDJHKVJHDSJHSJHVJSVADJHSJHVHIDSVAJHSAJHKDDASHIVDJUHDSAVJHJDSJVCDSVCVSGJCVDGJAVCGJHAVCGJKDVASUHJCVHUIKJDVUHCVJGHADSAVCHGDAAAAAAAAAAAAAAAAAASOUDOBENFICAISSOMEENVAIDECETENHOAGENICAQUEAQUALQUERENGRANDECESOUDEUMCLUBELUTADORQUENALUTACOMFERVORNUNCAENCONTROURIVALNESTENOSSOPORTUGALSERBENFIQUISTAÉTERNAALMAACHAMAIMENSAQUENOSCONQUISTAELEVAÀPALMAACHAMAIMENSADOSOLQUELANOCEURISONHOVEMBEIJARCOMUMORGULJOMUIYOSEUEDASCAMISOLASBERRANTESQUENOSCAMPOSACIBRARSAOPAPOILASSALTITANTES!";
    char *path = "/f12871t8756278687296318758721657826";
    char buffer[65537];
    // char second_buffer[65537];

    assert(tfs_init() != -1);

    int f;
    ssize_t r;

    f = tfs_open(path, TFS_O_CREAT);
    assert(f != -1);

    r = tfs_write(f, str, strlen(str));
    assert(r == strlen(str));

    assert(tfs_close(f) != -1);

    f = tfs_open(path, 0);
    assert(f != -1);

    r = tfs_read(f, buffer, sizeof(buffer) - 1);
    assert(r == strlen(str));

    buffer[r] = '\0';
    assert(strcmp(buffer, str) == 0);

    assert(tfs_close(f) != -1);

    tfs_copy_to_external_fs(path, "teste-copia.txt");

    printf(GRN "Successful test.\n" RESET);

    return 0;
}
